// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqordocjvjyonwobchhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impxb3Jkb2Nqdmp5b253b2JjaGhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NjkyOTcsImV4cCI6MjA2OTI0NTI5N30.xL9Yl1StPG-B_4QV7nXFZS7vmK9rGcT1bbMwcniJDkI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});